const DEV_DB_URI = "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
const TEST_DB_URI = "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
const MOCHA_TEST_TIMEOUT = 5000;

module.exports = {
 DEV_DB_URI,
 TEST_DB_URI,
 MOCHA_TEST_TIMEOUT
}
